---
permissions:
  can_manage_backups:
    permission_set_text: "L'utente potrÃ  creare e gestire file di backup relativi alla sua configurazione?"
    button_text: "ğŸ’¾ Backup & Restore"
    button_data: "backup_restore"
  can_manage_users:
    permission_set_text: "L'utente potrÃ  aggiungere e rimuovere altri utenti?\n\nâ˜ ï¸ <b>Usare con cautela</b>"
    button_text: "ğŸ‘¤ Utenti e Permessi"
    button_data: "user_menaging"
texts:
  overall_functioning:
    owner: None
    admin: "ğŸ’¡ <b>Informazioni Generali</b>\n\nSono in grado di controllare periodicamente la presenza di aggiornamenti 
    relativi ad applicazioni sul Play Store. Per funzionare, ho bisogno di tre informazioni:\n  1. il <u>link 
    all'applicazione</u> che ti interessa;\n  2. l'<u>intervallo di controllo</u> tra due check;\n  3. in quali 
    <u>condizioni</u> vuoi ricevere il messaggio.\n\nâ„¹ <b>Verrai guidato in ogni passaggio.</b> In caso di problemi, 
    contatta @AleLntr.\n\n1ï¸âƒ£ <b>Al Primo Avvio</b>\nVengono settate le impostazioni di default, utili al mio 
    funzionamento. Da ora, <b>tutti</b> i dati verranno salvati all'interno di alcune variabili permanenti. I valori 
    contenuti all'interno di queste variabili saranno salvati, ad intervalli regolari, all'interno di un file chiamato 
    <code>persistence</code> (Ã¨ un file senza estensione contenente caratteri non leggibili).\n\nâš ï¸ Il salvataggio di 
    tali informazioni sul file <code>persistence</code> serve per garantire che i dati non vengano persi in caso di 
    arresti anomali dello script del bot. <u>La rimozione di tale file, pertanto, comporta la cancellazione della sua 
    memoria</u> e, in tal caso, il bot dovrÃ  essere reimpostato, come ti accingi a fare.\n\nI valori che stai per 
    impostare costituiscono le <b>impostazioni di default</b>: l'<b>intervallo di check di default</b> â€“ se non viene 
    impostato per una certa applicazione â€“ e il <b>parametro sulla condizione di invio del messaggio</b>, di default, 
    che specifica se il messaggio andrÃ  mandato solo se viene rilevato un aggiornamento oppure ad ogni controllo.\n\n2ï¸âƒ£ 
    <b>Funzioni</b> â€“ Il bot consente alcune semplici operazioni, tra cui:\n\nğŸ”¸ <b>Aggiunta di applicazioni da 
    monitorare</b>\nL'aggiunta di un'applicazione puÃ² essere fatta tramite il passaggio del link al Play Store.\n\n
    ğŸ”¸ <b>Settaggio delle applicazioni</b>\nQuando un'applicazione viene aggiunta, Ã¨ richiesta l'impostazione di 
    controllo.\n\nğŸ”¸ <b>Modifica delle impostazioni di app giÃ  aggiunte</b>\nDa un apposito menu, sarÃ  possibile 
    cambiare le impostazioni relative ad un'applicazione precedentemente aggiunta.\n\nğŸ”¸ <b>Sospensione o rimozione di 
    un'applicazione</b>\nPotrai anche sospendere gli aggiornamenti e riattivarli in un secondo momento, o rimuovere 
    un'applicazione dall'elenco di quelle tracciate.\n\nğŸ”¸ <b>Lista delle applicazioni aggiunte</b>\nPotrai 
    visualizzare tutti i dettagli delle applicazioni che hai aggiunto (sospese e non).\n\nğŸ”¸ <b>Modifica delle 
    impostazioni di Default</b>\nTutti i valori possono essere cambiati tramite le impostazioni.\n\nğŸ”¸ <b>Lista degli 
    ultimi 10 controlli effettuati</b>\nPuoi visualizzare una lista degli ultimi check fatti, assieme ai dettagli su 
    eventuali aggiornamenti.\n\nğŸ†˜ In caso di problemi, controlla i file di log presenti nella cartella del progetto in 
    <code>/misc/logs</code> e contatta @AleLntr.\n\nâ¡ <b>Nota Importante</b> â€“ Per consentire al bot di inviarti 
    messaggi, ricordati di mantenere la chat attiva mantenendovi almeno un messaggio all'interno, altrimenti il bot 
    non ti potrÃ  scrivere.\n\nâš ï¸ Tieni inoltre presente che Telegram impone un limite di 30 messaggi al secondo, quindi 
    fai attenzione a non eccedere tale limite."
    allowed_users: "ğŸ’¡ <b>Informazioni Generali</b>\n\nâš ï¸ <u>L'admin @Linxay ha aggiunto il tuo ID alla whitelist</u>.
    Tieni presente che <b>puÃ² rimuoverlo</b> in qualunque momento o modificare i tuoi permessi.\n\nâ„¹ï¸ Sono in grado di 
    controllare periodicamente la presenza di aggiornamenti per tutte le applicazioni sul Play Store. Per funzionare, 
    ho bisogno di tre informazioni:\n  1. Il <u>link allâ€™applicazione</u> che ti interessa;\n  2. Lâ€™<u>intervallo di 
    controllo</u> tra due check;\n  3. In quali <u>condizioni</u> vuoi ricevere il messaggio.\n\nğŸ‘â€ğŸ—¨ <b>Verrai guidato 
    in ogni passaggio</b>. In caso di problemi, contatta @AleLntr.\n\n1ï¸âƒ£ <b>Al Primo Avvio</b>\nVengono settate le 
    impostazioni di default, utili al mio funzionamento. Da ora, <b>tutti</b> i dati verranno salvati allâ€™interno di 
    variabili permanenti. I valori contenuti allâ€™interno di queste variabili saranno salvati, ad intervalli regolari, 
    allâ€™interno di un file criptato. Questo meccanismo di salvataggio serve ad assicurare il mantenimento delle 
    informazioni in caso di arresti anomali.\n\nI valori che stai per impostare costituiscono le <b>impostazioni di 
    default</b>: lâ€™intervallo di check di default â€“ se non viene impostato per una certa applicazione â€“ e il parametro 
    sulla <b>condizione di invio del messaggio</b>, di default, che specifica se il messaggio andrÃ  mandato solo se 
    viene rilevato un aggiornamento oppure ad ogni controllo.\n\n<b>2ï¸âƒ£ Funzioni</b> â€“ Il bot consente alcune semplici 
    operazioni, tra cui:\n\n<b>ğŸ”¸ Aggiunta di applicazioni da monitorare</b> â€“ Lâ€™aggiunta di unâ€™applicazione puÃ² essere 
    fatta tramite il passaggio del link al Play Store.\n\n<b>ğŸ”¸ Settaggio delle applicazioni</b> â€“ Quando 
    unâ€™applicazione viene aggiunta, Ã¨ richiesta lâ€™impostazione dei valori di controllo.\n\n<b>ğŸ”¸ Modifica delle 
    impostazioni di app giÃ  aggiunte</b> â€“ Da un apposito menu, sarÃ  possibile cambiare le impostazioni relative ad 
    unâ€™applicazione precedentemente aggiunta.\n\n<b>ğŸ”¸ Sospensione o rimozione di unâ€™applicazione</b> â€“ Potrai anche 
    sospendere gli aggiornamenti e riattivarli in un secondo momento, o rimuovere unâ€™applicazione dallâ€™elenco di quelle 
    tracciate.\n\n<b>ğŸ”¸ Lista delle applicazioni aggiunte</b> â€“ Potrai visualizzare tutti i dettagli delle applicazioni 
    che hai  aggiunto (se ce ne sono).\n\n<b>ğŸ”¸ Modifica delle impostazioni di Default</b> â€“ Tutti i valori possono 
    essere cambiati tramite le impostazioni.\n\n<b>ğŸ”¸ Lista degli ultimi 10 controlli effettuati</b> â€“ Puoi visualizzare
     una lista degli ultimi check fatti, assieme ai dettagli su eventuali aggiornamenti.\n\n<b>â• Permessi Aggiuntivi</b>
      â€“ Queste funzioni possono essere concesse e modificate da @Linxay.\n\n<b>ğŸ”¹ Backup e Ripristino</b> â€“ Potrai 
    eseguire il backup di tutti i tuoi dati. Successivamente, in caso di perdita dei dati per errori imprevisti o 
    funzionamenti indesiderati, potrai ripristinarlo.\n\n<b>ğŸ†˜ In caso di problemi, contatta @Linxay, lâ€™admin principale
    , o @AleLntr, il creatore di questo bot.</b>\n\n<b>â„¹ Nota importante</b> â€“ Per consentire ai bot di inviarti 
    messaggi, ricordati di mantenere la chat attiva mantenendo almeno un messaggio allâ€™interno, altrimenti il bot non 
    ti potrÃ  scrivere.\n\n<b>âš ï¸ Tieni inoltre presente che Telegram impone un limite di 30 messaggi al secondo, quindi 
    fai attenzione a non eccedere tale limite.</b>\n"